import Image from 'next/image'
import FacebookIcon from '@material-ui/icons/Facebook';
import Button from '@material-ui/core/Button';
import { IconButton } from '@material-ui/core';
import TextField from '@material-ui/core/TextField';
import Head from "next/head"
import {useState,useEffect}from "react"
import { useDispatch, useSelector } from "react-redux";
import { adduser, selectCount } from "../redux/reducers/loginslice";
import { useRouter } from 'next/router'



import { auth, provider } from "../Components/firebase.js";


export default function Login(){
  const state = useSelector(selectCount);
  useEffect(()=>
    {
      localStorage.setItem("user",[state.name,state.photo])

},[state])

  const router = useRouter()


  //const [user,setuser]=useState([])

  const dispatch = useDispatch(adduser);

  const signIn = () => {

    auth
      .signInWithPopup(provider)
      .then((result) => {
        console.log(result);
        const newUser = {
          name: result.user.displayName,
          photo: result.user.photoURL,
        };
        dispatch(adduser(newUser))





//        props.setUser(newUser);
      })
      .catch((error) => {
        alert(error.message);
      });

  };



    return(

<div>

<div className="login">
<Head>
        <title>Instagram 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://freight.cargo.site/t/original/i/a0e492152aa8c83f66bb74972aff66529bbca0dce581d2f557a0e4b02f203824/Insta.png"
        />
      </Head>

    <div>
    <Image className="iphone__image" src="/phone.png" alt="phone"  width="600" height="800"/> 
    </div>
    <div className="login__form">
    <div className="login__form1">
        <div className="login__formname" style={{display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center"}}>
            <Image id="logo" src="/instagramlogo.png"width="95" height="95" />
       Instagram
</div>
<div className="login__input">

<TextField label="Phone number,username or email"  className="input"/>
{/* <input id="outlined-basic" variant="outlined"  className="input"/>
 */}<TextField className="input"  label="password"/>




<Button variant="contained" onClick={signIn}  className="login__button" >Login</Button>

<div style={{textAlign:"center",display:"flex"}}><hr width="80px"/>OR<hr width="80px"/></div>
<><div className="idjou" ><button onClick={signIn} className="Login__another"><FacebookIcon/><p>Log in with Facebook</p></button></div></>
<><button className="Login__another">Forgot password</button></>
</div>

</div>

    <div className="login__form2">
        Dont have an account ? <span style={{color:"blue"}}>Sign Up</span>
        </div>
    </div>




    </div>
    <footer  id="footer" style={{display:"flex"}}>
    <p>About</p><p>Help</p><p>API</p><p>Press</p><p>Job</p><p>Privacy</p><p>Terms</p><p>Location</p><p>Top Accounts</p><p>Hashtag</p><p>Langauge</p>
        </footer>
        <span id="las">© 2021 INSTAGRAM FROM FACEBOOK</span>
    </div>


    )
}
